### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by subdiv7** [mprib/rigmarole#12]
Hi, I came across your project and thought that perhaps this other discontinued project might help you create an add-on for Blender, with some modifications.(https://github.com/cgtinker/BlendArMocap)

**Comment by mprib** [comment]
Hi! Thank you for taking a look. I reached out to the maintainer of BlendArMocap awhile back but didn't hear anything. I've been wary of diving into the code itself both for licensing reasons and because I find its often more efficient to build things from the ground up than to work with large amounts of legacy code.

If you have an interest in motion capture for blender, the related project https://github.com/mprib/pyxy3d is in quite active development. I'll be updating docs on that over the coming week and am actively looking for user feedback. As that stabilizes I'll be able to invest more time in the Blender add-on side of things.

Appreciate you dropping a line!
